(define (domain pacman)
	(:requirements :typing)
	(:predicates (at [?x ?y])
				 (wall [?x ?y])
				 (pacman [?x ?y])
				 (abs [?x ?y ?eq]))
	(:action move
		:parameters (?c_x ?c_y ?n_x ?n_y)
		:precondition (and (at ?c_x ?c_y)
						   (or (= (abs ?c_x ?n_x) 1)
						       (= (abs ?c_y ?n_y) 1))
						   (not (and (= (abs ?c_x ?n_x) 1)
						       		 (= (abs ?c_y ?n_y) 1)))
						   (not (wall ?n_x ?n_y)))
		:effect (and (at ?n_x ?n_y)
					 (not (at ?c_x ?c_y))))
)