(define (domain pacman)
	(:requirements :typing)
	(:types num)
	(:predicates (at ?x ?y - num)
				 (wall ?x ?y - num)
				 (food ?x ?y - num)
				 (ghost ?x ?y - num)
				 (abs ?x ?y ?eq - num))
	(:action move
		:parameters (?c_x ?c_y ?n_x ?n_y - num)
		:precondition (and (at ?c_x ?c_y)
							(xor (abs ?c_x ?n_x 1)
								 (abs ?c_y ?n_y 1))
							(not (wall ?n_x ?n_y))
							(not (ghost ?n_x ?n_y)))
		:effect (and (at ?n_x ?n_y)
					 (not (at ?c_x ?c_y))
					 (not (food ?n_x ?n_y))))
)
